/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UIButton {
        "text": string | undefined;
        "type": string | undefined;
    }
}
declare global {
    interface HTMLUIButtonElement extends Components.UIButton, HTMLStencilElement {
    }
    var HTMLUIButtonElement: {
        prototype: HTMLUIButtonElement;
        new (): HTMLUIButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ui-button": HTMLUIButtonElement;
    }
}
declare namespace LocalJSX {
    interface UIButton {
        "text"?: string | undefined;
        "type"?: string | undefined;
    }
    interface IntrinsicElements {
        "ui-button": UIButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-button": LocalJSX.UIButton & JSXBase.HTMLAttributes<HTMLUIButtonElement>;
        }
    }
}
